### ISSUE TITLE
用arm64编译下（比如编译到iPhone 5s），hotspot没反应

### ISSUE THREAD

**Issue by supermaxJ** [heroims/HelloPanoramaGL#2]
不知道您在arm64下编译过没有，我发现在arm64下编译，hotspot是不响应的。不论是在iPhone5s真机上还是在arm64的模拟器下。我试了很多办法，但貌似找不出问题在哪。还望您看一下，是否有这样的问题。

**Comment by heroims** [comment]
暂时解决方案就是64位上跑32位你的项目应该是没设置 Architectures为 $(ARCHS_STANDARD_32_BIT)，过段时间进行处理

**Comment by fengyang0329** [comment]
非常感谢你的回复，期待你的下个解决方案。

**Comment by shaojiankui** [comment]
http://www.skyfox.org/ios-panoramagl-360-arm64-hotspot.html 我解决了64位这个问题...哈哈 看你改重力感应那么幸苦

**Comment by fengyang0329** [comment]
soga,非常感谢！

**Comment by heroims** [comment]
感谢
